USE `User`;

INSERT INTO `User` (`firstname`,`lastname`,`email`,`password`, `role`) 
    VALUES 	("Nathan","Fluckiger","nathan@fluckiger.ch","1234", "admin"),
            ("David","Jaquet","david@jaquet.ch","1234", "admin");

INSERT INTO `User` (`firstname`,`lastname`,`email`,`password`) 
	VALUES 	("Fuller","Maddox","non.enim@eratnonummyultricies.co.uk","IBK"),
			("Damian","Monroe","Nulla@consequatdolor.edu","FYL"),
			("Avram","Salinas","aliquam@pedemalesuada.edu","TSY"),
			("Randall","Harding","Phasellus.nulla.Integer@laoreetlectus.net","KCY"),
			("Hedley","Parrish","et@inlobortis.com","RIF"),
			("Hyatt","Robbins","In.mi.pede@vitae.org","CNV"),
			("Martin","Oconnor","Suspendisse.ac.metus@turpisNulla.co.uk","PKQ"),
			("Peter","Larsen","id@ultrices.co.uk","FFR"),
			("Malachi","May","rutrum.urna.nec@velfaucibus.com","FJZ"),
			("George","Carpenter","quam@Aliquamultricesiaculis.co.uk","KUC"),
			("Orson","Brock","ipsum.dolor@pharetranibh.edu","LPV"),
			("Amery","Coffey","libero@semvitaealiquam.org","SQZ"),
			("Edan","Kelley","at.iaculis.quis@commodotincidunt.co.uk","ARW"),
			("Tarik","Camacho","sodales.purus@enimNunc.net","DTS"),
			("Lucas","Mack","Integer.tincidunt@commodo.net","WMP"),
			("Adam","Jimenez","ac.mi@tellusimperdietnon.com","BTO"),
			("Zachery","Mueller","lorem@orciUtsemper.co.uk","QFR"),
			("Mark","Hester","libero@dolorvitaedolor.co.uk","TQE"),
			("Damon","Salazar","ultrices.Duis@semperrutrumFusce.com","VBT"),
			("Grady","Huber","risus.at.fringilla@risusDonecegestas.edu","EZG"),
			("Sawyer","Sweet","ligula.tortor.dictum@Donecnibh.ca","DLB"),
			("Noble","Vega","pellentesque.tellus.sem@egetmollis.edu","VFV"),
			("Barrett","Solis","Quisque.libero.lacus@sagittisplacerat.co.uk","UYH"),
			("Forrest","Zamora","sagittis.semper.Nam@eudolor.net","XMA"),
			("Tanek","Mcintyre","dolor.dolor.tempus@pede.net","FRS"),
			("Cyrus","Herrera","volutpat.Nulla.facilisis@arcuMorbisit.net","LIS"),
			("Randall","Bush","nonummy.Fusce@Cras.org","QCD"),
			("Avram","Hoffman","enim@Vivamusmolestie.co.uk","VPJ"),
			("Geoffrey","Nixon","tincidunt.pede.ac@lobortis.edu","DIE"),
			("Jonas","Larsen","tristique@Etiamligulatortor.com","BXR"),
			("Thomas","Gilbert","eget@Donec.ca","LWQ"),
			("Otto","Dunn","orci.Ut@accumsanconvallis.co.uk","HVU"),
			("Isaac","Patel","cursus@nibhlacinia.edu","GHU"),
			("Zeph","Morris","viverra@convallisdolor.net","MJF"),
			("Beck","Harrington","lacus.Etiam@non.org","BYS"),
			("Garrison","Anderson","bibendum.Donec.felis@temporbibendum.edu","ZUV"),
			("Deacon","Ray","felis.orci@Sednulla.ca","DKK"),
			("Duncan","Herman","placerat.eget@semperNam.org","QKM"),
			("Drew","Jones","tellus@necenimNunc.com","ZHR"),
			("Daquan","Hudson","luctus@nisi.co.uk","LBM"),
			("Wang","Cochran","ut.ipsum@arcuetpede.co.uk","OGD"),
			("Kuame","Fox","metus.In@risusvarius.com","ZXS"),
			("Lance","Rosa","nulla.Donec@ligulatortor.co.uk","RAP"),
			("Abel","Christian","lorem.ac@aliquam.org","TXC"),
			("Gareth","Cooke","vitae.diam.Proin@pharetra.co.uk","VFH"),
			("Cyrus","Solis","augue@Suspendisse.net","QJO"),
			("Lawrence","Willis","sit@velitegestas.org","CRZ"),
			("Evan","Cross","Etiam.vestibulum@imperdietullamcorper.ca","ARD"),
			("Kane","Shaffer","sed.leo.Cras@enimEtiamimperdiet.edu","OJH"),
			("Zephania","Shaffer","leo.Cras@blanditviverra.edu","APX"),
			("Vernon","Koch","tortor@vulputatelacusCras.uk","ZFD"),
			("Tanner","Brewer","sociis.natoque@urnaNullamlobortis.com","LPM"),
			("Dorian","Kramer","Mauris@aliquetsem.com","VFW"),
			("Gareth","Contreras","tristique@lectusquis.org","JHD"),
			("Marsden","Roach","accumsan.convallis.ante@semegestasblandit.net","ZIK"),
			("Victor","Mccormick","eu.lacus.Quisque@sociis.net","HXA"),
			("Fuller","Stein","vel.venenatis@mauris.net","WSO"),
			("Andrew","George","sodales@amet.co.uk","DIY"),
			("Wayne","Greene","tellus.Suspendisse@ultrices.edu","RRQ"),
			("Reece","Carey","tempor.bibendum.Donec@Maecenas.co.uk","KBW"),
			("Theodore","Brooks","convallis@ornarefacilisiseget.co.uk","DGX"),
			("Abdul","Vazquez","quam.dignissim.pharetra@Nunclectuspede.edu","YSC"),
			("Hasad","Price","habitant.morbi@feugiat.com","XTR"),
			("Wade","Riddle","libero@Donec.com","LPE"),
			("Gregory","Justice","Fusce.aliquam.enim@risusatfringilla.net","MUM"),
			("Stone","Tucker","at@Praesenteudui.edu","OHV"),
			("Blaze","Summers","Nunc.ullamcorper.velit@enim.org","EJF"),
			("Laith","Blanchard","ut.pharetra.sed@necmaurisblandit.edu","SUC"),
			("Ryder","Kramer","Donec.tincidunt@pretiumaliquet.ca","EKE"),
			("Kibo","Fletcher","mi.felis@eget.co.uk","DDO");
