USE `User`;

INSERT INTO `User` (`firstname`,`lastname`,`email`,`password`, `role`) 
    VALUES 	("Nathan","Fluckiger","nathan@fluckiger.ch","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82", "admin"),
            ("David","Jaquet","david@jaquet.ch","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82", "admin");

INSERT INTO `User` (`firstname`,`lastname`,`email`,`password`) 
	VALUES 	("Fuller","Maddox","non.enim@eratnonummyultricies.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Damian","Monroe","Nulla@consequatdolor.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Avram","Salinas","aliquam@pedemalesuada.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Randall","Harding","Phasellus.nulla.Integer@laoreetlectus.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Hedley","Parrish","et@inlobortis.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Hyatt","Robbins","In.mi.pede@vitae.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Martin","Oconnor","Suspendisse.ac.metus@turpisNulla.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Peter","Larsen","id@ultrices.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Malachi","May","rutrum.urna.nec@velfaucibus.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("George","Carpenter","quam@Aliquamultricesiaculis.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Orson","Brock","ipsum.dolor@pharetranibh.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Amery","Coffey","libero@semvitaealiquam.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Edan","Kelley","at.iaculis.quis@commodotincidunt.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Tarik","Camacho","sodales.purus@enimNunc.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Lucas","Mack","Integer.tincidunt@commodo.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Adam","Jimenez","ac.mi@tellusimperdietnon.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Zachery","Mueller","lorem@orciUtsemper.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Mark","Hester","libero@dolorvitaedolor.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Damon","Salazar","ultrices.Duis@semperrutrumFusce.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Grady","Huber","risus.at.fringilla@risusDonecegestas.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Sawyer","Sweet","ligula.tortor.dictum@Donecnibh.ca","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Noble","Vega","pellentesque.tellus.sem@egetmollis.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Barrett","Solis","Quisque.libero.lacus@sagittisplacerat.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Forrest","Zamora","sagittis.semper.Nam@eudolor.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Tanek","Mcintyre","dolor.dolor.tempus@pede.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Cyrus","Herrera","volutpat.Nulla.facilisis@arcuMorbisit.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Randall","Bush","nonummy.Fusce@Cras.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Avram","Hoffman","enim@Vivamusmolestie.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Geoffrey","Nixon","tincidunt.pede.ac@lobortis.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Jonas","Larsen","tristique@Etiamligulatortor.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Thomas","Gilbert","eget@Donec.ca","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Otto","Dunn","orci.Ut@accumsanconvallis.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Isaac","Patel","cursus@nibhlacinia.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Zeph","Morris","viverra@convallisdolor.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Beck","Harrington","lacus.Etiam@non.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Garrison","Anderson","bibendum.Donec.felis@temporbibendum.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Deacon","Ray","felis.orci@Sednulla.ca","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Duncan","Herman","placerat.eget@semperNam.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Drew","Jones","tellus@necenimNunc.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Daquan","Hudson","luctus@nisi.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Wang","Cochran","ut.ipsum@arcuetpede.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Kuame","Fox","metus.In@risusvarius.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Lance","Rosa","nulla.Donec@ligulatortor.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Abel","Christian","lorem.ac@aliquam.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Gareth","Cooke","vitae.diam.Proin@pharetra.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Cyrus","Solis","augue@Suspendisse.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Lawrence","Willis","sit@velitegestas.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Evan","Cross","Etiam.vestibulum@imperdietullamcorper.ca","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Kane","Shaffer","sed.leo.Cras@enimEtiamimperdiet.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Zephania","Shaffer","leo.Cras@blanditviverra.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Vernon","Koch","tortor@vulputatelacusCras.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Tanner","Brewer","sociis.natoque@urnaNullamlobortis.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Dorian","Kramer","Mauris@aliquetsem.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Gareth","Contreras","tristique@lectusquis.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Marsden","Roach","accumsan.convallis.ante@semegestasblandit.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Victor","Mccormick","eu.lacus.Quisque@sociis.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Fuller","Stein","vel.venenatis@mauris.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Andrew","George","sodales@amet.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Wayne","Greene","tellus.Suspendisse@ultrices.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Reece","Carey","tempor.bibendum.Donec@Maecenas.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Theodore","Brooks","convallis@ornarefacilisiseget.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Abdul","Vazquez","quam.dignissim.pharetra@Nunclectuspede.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Hasad","Price","habitant.morbi@feugiat.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Wade","Riddle","libero@Donec.com","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Gregory","Justice","Fusce.aliquam.enim@risusatfringilla.net","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Stone","Tucker","at@Praesenteudui.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Blaze","Summers","Nunc.ullamcorper.velit@enim.org","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Laith","Blanchard","ut.pharetra.sed@necmaurisblandit.edu","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Ryder","Kramer","Donec.tincidunt@pretiumaliquet.ca","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82"),
			("Kibo","Fletcher","mi.felis@eget.co.uk","$2a$10$4qlJgTw4BfYM2b4oAxhusOlojnYSsvNOlJ1a5NariiIvtkzr7.h82");
