version: '3'
services:
   mysql_auth:
      build: ../../docker-image/mysql/auth
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "3306:3306"
      volumes:
         - data:/data/db
   mysql_official:
      build: ../../docker-image/mysql/officialLeague
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "3307:3306"
      volumes:
         - data:/data/db
         
         
   phpmyadmin:
      build: ../../docker-image/phpmyadmin
      environment:
         PMA_HOSTS: mysql_auth, mysql_official
         MYSQL_ROOT_PASSWORD: admin
      ports:
         - "6060:80"
         
volumes:
    data:
